# Generated by Django 4.2 on 2023-06-07 15:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carriage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carriage_num", models.PositiveSmallIntegerField(verbose_name="车厢号")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUS", "商务舱"),
                            ("FST", "一等舱"),
                            ("SND", "二等舱"),
                            ("SOF", "软卧"),
                            ("HAW", "硬卧"),
                            ("HAZ", "硬座"),
                        ],
                        max_length=3,
                        verbose_name="车厢类型",
                    ),
                ),
                ("total_num", models.PositiveSmallIntegerField(verbose_name="座位总数")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="价格",
                    ),
                ),
            ],
            options={
                "verbose_name": "车厢",
                "verbose_name_plural": "车厢",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="价格",
                    ),
                ),
                ("order_status", models.CharField(max_length=3, verbose_name="订单状态")),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=5, unique=True, verbose_name="车站名"),
                ),
                ("city", models.CharField(max_length=10, verbose_name="城市名")),
            ],
            options={
                "verbose_name": "车站",
                "verbose_name_plural": "车站",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="车次"),
                ),
                (
                    "train_type",
                    models.CharField(
                        choices=[("HSR", "高铁"), ("REG", "普通车")],
                        default="HSR",
                        max_length=8,
                        verbose_name="车次类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "列车",
                "verbose_name_plural": "列车",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("remaining_count", models.PositiveSmallIntegerField()),
                (
                    "carriage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="train.carriage"
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="train.train"
                    ),
                ),
            ],
            options={
                "verbose_name": "车票",
                "verbose_name_plural": "车票",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.TimeField(verbose_name="到达时间")),
                ("duration", models.DurationField(verbose_name="停留时间")),
                ("sequence", models.IntegerField(verbose_name="序号")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train.station",
                        verbose_name="车站",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train.train",
                        verbose_name="车次",
                    ),
                ),
            ],
            options={
                "verbose_name": "途径站",
                "verbose_name_plural": "途径站",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_num", models.PositiveSmallIntegerField()),
                ("seat_location", models.CharField(max_length=1)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="train.ticket"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassengerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="价格",
                    ),
                ),
                ("is_rebooked", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="train.order"
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.passenger"
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="train.seat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="end_stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_stop_order",
                to="train.stop",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="start_stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_stop_order",
                to="train.stop",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="train.train",
                verbose_name="车次",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="carriage",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="train.train",
                verbose_name="所属车次",
            ),
        ),
    ]
